### ISSUE TITLE
カスタムイメージの作成 リンクページの差し替え

### ISSUE THREAD

**Issue by collelog** [mirakc/dekiru-mirakc#2]
[カスタムイメージの作成](https://mirakc.github.io/dekiru-mirakc/custom_image.html)

文中の「[tv-recorder/mirakc](https://github.com/collelog/tv-recorder/tree/master/mirakc)」ですが、Dockerfileを管理するリポジトリを「[tv-recorder-dockerfile/mirakc](https://github.com/collelog/tv-recorder-dockerfile/tree/master/mirakc)」に変更しておりますので、お手数おかけしますが該当ページにも反映して頂ければ幸いです。

**Comment by masnagam** [comment]
@collelog 報告ありがとうございます．修正しました．
